### ISSUE TITLE
Critical: Argon2 flawed salt usage

### ISSUE THREAD

**Issue by hcksw** [Brassack/swift-data-processor#1]
The Argon2 hashes are not using the salt properly. Whatever value I change it to, it always uses a default salt of “somesalt”. I have tested this against Argon2 hashes produced using the reference Argon2 C implementation on Mac OS and by analysing the encoded output which always decodes to “somesalt” for the salt.

**Comment by Brassack** [comment]
@hcksw  Thanks you very much for bug report!
 For some reason I missed it.
I have pushed fix to repo and submit update to App Store review.
Cheers.

**Comment by Brassack** [comment]
Fix in appstore @hcksw
